use_frameworks!

platform :ios, '9.0'

target 'lsj-PrivateProtocolAlert_Example' do
  pod 'lsj-PrivateProtocolAlert', :path => '../'

  target 'lsj-PrivateProtocolAlert_Tests' do
    inherit! :search_paths

    
  end
end
